pr: none
jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    variables:
      - name: BUILDSECMON_OPT_IN
        value: true
    steps:
      - task: Bash@3
        displayName: "Base64 decodes and pipes the GPG key content into the secret file"
        env:
          GPG_KEY_CONTENT: $(gpgContent)
          SIGNING_SECRET_KEY_RING_FILE: $(gpgSecretFilePath)
        inputs:
          targetType: "inline"
          script: |
            # Write your commands here
            sudo bash -c "echo '$GPG_KEY_CONTENT' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
            ls